-- MySQL Script generated by MySQL Workbench
-- Mon Feb 16 16:22:47 2020
-- Model: release-mdb    Version: 3.0

-- Rooters RDB Model
-- (c) Rooters, Inc. 2020

-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';


-- -----------------------------------------------------
-- Schema rooters_rdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rooters_rdb` DEFAULT CHARACTER SET utf8mb4 ;
USE `rooters_rdb` ;

-- -----------------------------------------------------
-- Table `rooters_rdb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rooters_rdb`.`user` (
  `user_id` BINARY(16) NOT NULL,
  `email` VARCHAR(129) NOT NULL,
  `first_name` VARCHAR(129) NOT NULL,
  `last_name` VARCHAR(129) NULL,
  `password` VARCHAR(129) NULL,
  `contact` VARCHAR(129) NULL DEFAULT '',
  `deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `referral_code` VARCHAR(129) NULL,
  `role` VARCHAR(129) NOT NULL,
  `auth_type` VARCHAR(129) NOT NULL DEFAULT 'INTERNAL',
  `created` DATETIME(3) NOT NULL,
  `created_by` VARCHAR(129) NOT NULL,
  `modified` DATETIME(3) NULL,
  `modified_by` VARCHAR(129) NULL,
  UNIQUE INDEX `idk_user_email_index_1` (`email` ASC),
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `rooters_rdb`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rooters_rdb`.`address` (
 `id` BINARY(16) NOT NULL,
  `user_id` BINARY(16) NOT NULL,
  `street_address` VARCHAR(129) NOT NULL,
  `city` VARCHAR(129) NOT NULL DEFAULT '',
  `state` VARCHAR(129) NOT NULL,
  `country` VARCHAR(129) NOT NULL,
  `zip_code` VARCHAR (6) NOT NULL,
  `created` DATETIME(3) NOT NULL,
  `created_by` VARCHAR(129) NOT NULL,
  `modified` DATETIME(3) NULL,
  `modified_by` VARCHAR(129) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_address_user_1dk_idx` (`user_id` ASC),
  CONSTRAINT `fk_address_user_1dk`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `rooters_rdb`.`password`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rooters_rdb`.`password` (
  `id` BINARY(16) NOT NULL,
  `user_id` BINARY(16) NOT NULL,
  `hash` VARCHAR(129) NOT NULL,
  `code` VARCHAR(129) NOT NULL,
  `expired` TINYINT(1) NOT NULL DEFAULT 0,
  `created` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_password_user_fk1`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `rooters_rdb`.`operator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rooters_rdb`.`operator` (
  `operator_id` BINARY(16) NOT NULL,
  `name` VARCHAR(129) NOT NULL,
  `gst_no` VARCHAR(129) NOT NULL,
  `street_address` VARCHAR(129) NOT NULL,
  `city` VARCHAR(129) NOT NULL DEFAULT '',
  `state` VARCHAR(129) NOT NULL,
  `country` VARCHAR(129) NOT NULL,
  `zip_code` VARCHAR (6) NOT NULL,
  `created` DATETIME(3) NOT NULL,
  `created_by` VARCHAR(129) NOT NULL,
  `modified` DATETIME(3) NULL,
  `modified_by` VARCHAR(129) NULL,
  PRIMARY KEY (`operator_id`),
  UNIQUE INDEX `idk_gst_no_index_1` (`gst_no` ASC)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `rooters_rdb`.`bus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rooters_rdb`.`bus` (
  `bus_id` BINARY(16) NOT NULL,
  `name` VARCHAR(129) NOT NULL,
  `bus_no` VARCHAR(129) NOT NULL,
  `operator_id` BINARY(16) NOT NULL,
  `seat_type` VARCHAR(129) NOT NULL,
  `bus_type` VARCHAR(129) NOT NULL,
  `registration_date` DATETIME(3) NOT NULL,
  `registered_city_area_id` BINARY(16) NOT NULL,
  `created` DATETIME(3) NOT NULL,
  `created_by` VARCHAR(129) NOT NULL,
  `modified` DATETIME(3) NULL,
  `modified_by` VARCHAR(129) NULL,
  PRIMARY KEY (`bus_id`),
  UNIQUE INDEX `idk_bus_no_index_1` (`bus_no` ASC),
  CONSTRAINT `fk_bus_operator_1`
        FOREIGN KEY (`operator_id`)
        REFERENCES `rooters_rdb`.`operator` (`operator_id`)
        ON DELETE CASCADE
        ON UPDATE NO ACTION,
  CONSTRAINT `fk_bus_registered_city_area_2`
        FOREIGN KEY (`registered_city_area_id`)
        REFERENCES `rooters_rdb`.`city_area` (`city_area_id`)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `rooters_rdb`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rooters_rdb`.`city` (
 `city_id` BINARY(16) NOT NULL,
  `name` VARCHAR(129) NOT NULL,
  `state` VARCHAR(129) NOT NULL,
  `created` DATETIME(3) NOT NULL,
  `created_by` VARCHAR(129) NOT NULL,
  `modified` DATETIME(3) NULL,
  `modified_by` VARCHAR(129) NULL,
  PRIMARY KEY (`city_id`),
  UNIQUE INDEX `idk_city_index_1` (`name` ASC)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `rooters_rdb`.`city_area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rooters_rdb`.`city_area` (
 `city_area_id` BINARY(16) NOT NULL,
  `name` VARCHAR(129) NOT NULL,
  `city_id` BINARY(16) NOT NULL,
  `zip_code` VARCHAR(129) NOT NULL,
  `created` DATETIME(3) NOT NULL,
  `created_by` VARCHAR(129) NOT NULL,
  `modified` DATETIME(3) NULL,
  `modified_by` VARCHAR(129) NULL,
  PRIMARY KEY (`city_area_id`),
  UNIQUE INDEX `idk_city_index_1` (`name` ASC),
  CONSTRAINT `fk_city_area_1`
        FOREIGN KEY (`city_id`)
        REFERENCES `rooters_rdb`.`city` (`city_id`)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `rooters_rdb`.`route`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rooters_rdb`.`route` (
 `route_id` BINARY(16) NOT NULL,
 `route_group_id` BINARY(16) NOT NULL,
 `order_value` INT(11) NOT NULL,
  `source_area_id` BINARY(16) NOT NULL,
  `destination_area_id` BINARY(16) NOT NULL,
  `bus_id` BINARY(16) NOT NULL,
  `created` DATETIME(3) NOT NULL,
  `created_by` VARCHAR(129) NOT NULL,
  `modified` DATETIME(3) NULL,
  `modified_by` VARCHAR(129) NULL,
  PRIMARY KEY (`route_id`),
  CONSTRAINT `fk_source_city_area_1`
        FOREIGN KEY (`source_area_id`)
        REFERENCES `rooters_rdb`.`city_area` (`city_area_id`)
        ON DELETE CASCADE
        ON UPDATE NO ACTION,
  CONSTRAINT `fk_destination_city_area_2`
        FOREIGN KEY (`destination_area_id`)
        REFERENCES `rooters_rdb`.`city_area` (`city_area_id`)
        ON DELETE CASCADE
        ON UPDATE NO ACTION,
  CONSTRAINT `fk_route_bus_3`
        FOREIGN KEY (`bus_id`)
        REFERENCES `rooters_rdb`.`bus` (`bus_id`)
        ON DELETE CASCADE
        ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `rooters_rdb`.`bus_availability`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rooters_rdb`.`bus_availability` (
 `bus_availability_id` BINARY(16) NOT NULL,
 `route_group_id` BINARY(16) NOT NULL,
  `bus_id` BINARY(16) NOT NULL,
  `available_date` DATETIME(3) NOT NULL,
  `available_seat` INT(11) NOT NULL,
  `created` DATETIME(3) NOT NULL,
  `created_by` VARCHAR(129) NOT NULL,
  `modified` DATETIME(3) NULL,
  `modified_by` VARCHAR(129) NULL,
  PRIMARY KEY (`bus_availability_id`),
  CONSTRAINT `fk_bus_availability_1`
        FOREIGN KEY (`bus_id`)
        REFERENCES `rooters_rdb`.`bus` (`bus_id`)
        ON DELETE CASCADE
        ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `rooters_rdb`.`passenger`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rooters_rdb`.`passenger` (
  `passenger_id` BINARY(16) NOT NULL,
  `email` VARCHAR(129) NOT NULL,
  `first_name` VARCHAR(129) NOT NULL,
  `last_name` VARCHAR(129) NULL,
  `gender` VARCHAR(129) NULL,
  `contact` VARCHAR(129) NULL DEFAULT '',
  `route_id` BINARY(16)  NOT NULL,
  `created` DATETIME(3) NOT NULL,
  `created_by` VARCHAR(129) NOT NULL,
  `modified` DATETIME(3) NULL,
  `modified_by` VARCHAR(129) NULL,
  UNIQUE INDEX `idk_passenger_email_index_1` (`email` ASC),
  PRIMARY KEY (`passenger_id`),
  CONSTRAINT `fk_passenger_route_1`
        FOREIGN KEY (`route_id`)
        REFERENCES `rooters_rdb`.`route` (`route_id`)
        ON DELETE CASCADE
        ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `rooters_rdb`.`booking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rooters_rdb`.`booking` (
  `booking_id` BINARY(16) NOT NULL,
  `booking_code` VARCHAR(129) NOT NULL,
  `seat_no` VARCHAR(129) NOT NULL,
  `bus_availability_id` BINARY(16) NOT NULL,
  `passenger_id` BINARY(16) NOT NULL,
  `created` DATETIME(3) NOT NULL,
  `created_by` VARCHAR(129) NOT NULL,
  `modified` DATETIME(3) NULL,
  `modified_by` VARCHAR(129) NULL,
  PRIMARY KEY (`booking_id`),
  CONSTRAINT `fk_bus_availability_route_1`
        FOREIGN KEY (`bus_availability_id`)
        REFERENCES `rooters_rdb`.`bus_availability` (`bus_availability_id`)
        ON DELETE CASCADE
        ON UPDATE NO ACTION,
  CONSTRAINT `fk_booking_passenger_route_1`
        FOREIGN KEY (`passenger_id`)
        REFERENCES `rooters_rdb`.`passenger` (`passenger_id`)
        ON DELETE CASCADE
        ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `rooters_rdb` ;

-- -----------------------------------------------------
-- function uuid_str
-- -----------------------------------------------------

DELIMITER $$
USE `rooters_rdb`$$
CREATE FUNCTION uuid_str(b BINARY(16))
  RETURNS CHAR(36) DETERMINISTIC
  BEGIN
    DECLARE hex CHAR(32);
    SET hex = HEX(b);
    RETURN lower(CONCAT(LEFT(hex, 8), '-', MID(hex, 9,4), '-', MID(hex, 13,4), '-', MID(hex, 17,4), '-', RIGHT(hex, 12)));
  END$$

DELIMITER ;

-- -----------------------------------------------------
-- function uuid_bin
-- -----------------------------------------------------

DELIMITER $$
USE `rooters_rdb`$$
CREATE FUNCTION uuid_bin(s CHAR(36))
  RETURNS BINARY(16) DETERMINISTIC
  RETURN UNHEX(CONCAT(LEFT(s, 8), MID(s, 10, 4), MID(s, 15, 4), MID(s, 20, 4), RIGHT(s, 12)))$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
