# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.16.3

pipelines:
  default:
    - step:
        name: Deploy to staging
        deployment: DEV
        caches:
          - node
        script:
          - npm install
          - npm run build
    
  