-- MySQL Script generated by MySQL Workbench
-- Mon Feb 16 16:22:47 2020
-- Model: release-mdb    Version: 3.0

-- Rooters RDB Model
-- (c) Rooters, Inc. 2020

-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';


-- -----------------------------------------------------
-- Schema rooters_rdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rooters_rdb` DEFAULT CHARACTER SET utf8mb4 ;
USE `rooters_rdb` ;

-- -----------------------------------------------------
-- Table `rooters_rdb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rooters_rdb`.`user` (
  `user_id` BINARY(16) NOT NULL,
  `email` VARCHAR(129) NOT NULL,
  `first_name` VARCHAR(129) NOT NULL,
  `last_name` VARCHAR(129) NULL,
  `department_type` VARCHAR(129) NOT NULL,
  `created` DATETIME(3) NOT NULL,
  `created_by` VARCHAR(129) NOT NULL,
  `modified` DATETIME(3) NULL,
  `modified_by` VARCHAR(129) NULL,
  UNIQUE INDEX `idk_user_email_index_1` (`email` ASC),
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


USE `rooters_rdb` ;

-- -----------------------------------------------------
-- function uuid_str
-- -----------------------------------------------------

DELIMITER $$
USE `rooters_rdb`$$
CREATE FUNCTION uuid_str(b BINARY(16))
  RETURNS CHAR(36) DETERMINISTIC
  BEGIN
    DECLARE hex CHAR(32);
    SET hex = HEX(b);
    RETURN lower(CONCAT(LEFT(hex, 8), '-', MID(hex, 9,4), '-', MID(hex, 13,4), '-', MID(hex, 17,4), '-', RIGHT(hex, 12)));
  END$$

DELIMITER ;

-- -----------------------------------------------------
-- function uuid_bin
-- -----------------------------------------------------

DELIMITER $$
USE `rooters_rdb`$$
CREATE FUNCTION uuid_bin(s CHAR(36))
  RETURNS BINARY(16) DETERMINISTIC
  RETURN UNHEX(CONCAT(LEFT(s, 8), MID(s, 10, 4), MID(s, 15, 4), MID(s, 20, 4), RIGHT(s, 12)))$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;